/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection {
  'backgroundColor' : string,
  'title' : string,
  'content' : string,
  'layout' : LayoutOption,
  'image' : string,
  'textColor' : string,
}
export interface Apartment {
  'id' : string,
  'city' : string,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'isActive' : boolean,
  'address' : string,
  'bookingUrl' : string,
  'photos' : Array<string>,
}
export interface ApartmentsSection {
  'backgroundColor' : string,
  'title' : string,
  'layout' : LayoutOption,
  'description' : string,
  'backgroundImage' : string,
  'textColor' : string,
}
export interface Artist {
  'id' : string,
  'bio' : string,
  'galleryImages' : Array<string>,
  'name' : string,
  'artworks' : Array<string>,
  'photo' : string,
}
export interface Artwork {
  'id' : string,
  'galleryImages' : Array<string>,
  'title' : string,
  'artistId' : string,
  'description' : string,
  'photo' : string,
  'price' : [] | [bigint],
  'isForSale' : boolean,
}
export interface AuraCollectionSection {
  'backgroundColor' : string,
  'title' : string,
  'contactInfo' : ContactInfo,
  'auraCollectionMainImageKey' : [] | [string],
  'showOnLandingPage' : boolean,
  'layout' : LayoutOption,
  'description' : string,
  'sectionTexts' : SectionTexts,
  'featuredArtworks' : Array<string>,
  'backgroundImage' : string,
  'featuredArtists' : Array<string>,
  'textColor' : string,
}
export type CardStyle = { 'minimal' : null } |
  { 'classic' : null } |
  { 'modern' : null };
export interface CityGuideEntry {
  'id' : string,
  'title' : string,
  'externalLink' : [] | [string],
  'sortOrder' : bigint,
  'description' : string,
  'imageKey' : [] | [string],
  'pdfKey' : [] | [string],
  'visible' : boolean,
  'category' : string,
}
export interface ContactInfo {
  'contactText' : string,
  'socialLinks' : Array<SocialLink>,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface ContactSubmission {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface ExclusiveService {
  'id' : string,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'imageKey' : [] | [string],
  'visible' : boolean,
  'category' : string,
  'priceInfo' : [] | [string],
  'requestLink' : [] | [string],
}
export interface ExperiencePage {
  'backgroundColor' : string,
  'title' : string,
  'layout' : LayoutOption,
  'description' : string,
  'highlights' : Array<Highlight>,
  'backgroundImage' : string,
  'sections' : Array<ExperienceSection>,
  'cardStyle' : CardStyle,
  'textColor' : string,
}
export interface ExperienceSection {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'animationType' : string,
  'layout' : LayoutOption,
  'description' : string,
  'isActive' : boolean,
  'videos' : Array<string>,
  'images' : Array<string>,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface FooterSection {
  'backgroundColor' : string,
  'contactInfo' : string,
  'socialLinks' : Array<string>,
  'layout' : LayoutOption,
  'textColor' : string,
}
export interface HeroSection {
  'backgroundColor' : string,
  'title' : string,
  'layout' : LayoutOption,
  'backgroundImage' : string,
  'textColor' : string,
  'subtitle' : string,
}
export interface Highlight {
  'id' : string,
  'title' : string,
  'icon' : string,
  'description' : string,
  'isActive' : boolean,
}
export type LayoutOption = { 'grid' : null } |
  { 'list' : null } |
  { 'centered' : null } |
  { 'simple' : null } |
  { 'leftImage' : null } |
  { 'gallery' : null };
export interface LegalPage {
  'backgroundColor' : string,
  'title' : string,
  'content' : string,
  'lastUpdated' : bigint,
  'textColor' : string,
}
export type LogoDisplayLocation = { 'both' : null } |
  { 'footer' : null } |
  { 'header' : null };
export interface MapMarker {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'website' : [] | [string],
  'imageKey' : [] | [string],
  'address' : string,
  'visible' : boolean,
  'category' : string,
}
export interface SectionTexts {
  'featuredText' : string,
  'discoverText' : string,
}
export interface SiteConfig {
  'defaultCollectionImage' : string,
  'aboutSection' : AboutSection,
  'heroSection' : HeroSection,
  'footerSection' : FooterSection,
  'artistDetailPageBackgroundColor' : string,
  'defaultHeroImage' : string,
  'logoDisplayLocation' : LogoDisplayLocation,
  'defaultArtworkImage' : string,
  'apartmentsSection' : ApartmentsSection,
  'headerTextColor' : string,
  'accentColor' : string,
  'logoPath' : string,
  'logoSize' : bigint,
  'language' : string,
  'defaultApartmentImage' : string,
  'auraCollectionPageBackgroundColor' : string,
  'defaultExperienceImage' : string,
  'defaultArtistImage' : string,
  'experiencePage' : ExperiencePage,
  'contactEmail' : string,
  'landingPageBackgroundColor' : string,
  'logoPlaceholderPath' : string,
  'defaultApartmentsImage' : string,
  'apartmentsPageBackgroundColor' : string,
  'bookingUrl' : string,
  'auraCollectionSection' : AuraCollectionSection,
  'textColor' : string,
  'apartmentDetailPageBackgroundColor' : string,
  'artworkDetailPageBackgroundColor' : string,
  'defaultAboutImage' : string,
}
export interface SocialLink { 'url' : string, 'platform' : string }
export interface Testimonial {
  'id' : string,
  'sortOrder' : bigint,
  'date' : string,
  'name' : string,
  'text' : string,
  'authorPhoto' : [] | [Uint8Array],
  'stars' : bigint,
  'visible' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addDraftApartment' : ActorMethod<[Apartment], undefined>,
  'addDraftArtist' : ActorMethod<[Artist], undefined>,
  'addDraftArtwork' : ActorMethod<[Artwork], undefined>,
  'addDraftCityGuideEntry' : ActorMethod<[CityGuideEntry], undefined>,
  'addDraftExclusiveService' : ActorMethod<[ExclusiveService], undefined>,
  'addDraftMapMarker' : ActorMethod<[MapMarker], undefined>,
  'addDraftTestimonial' : ActorMethod<[Testimonial], undefined>,
  'addExperienceHighlight' : ActorMethod<[Highlight], undefined>,
  'addExperienceSection' : ActorMethod<[ExperienceSection], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDraftApartment' : ActorMethod<[string], undefined>,
  'deleteDraftArtist' : ActorMethod<[string], undefined>,
  'deleteDraftArtwork' : ActorMethod<[string], undefined>,
  'deleteDraftCityGuideEntry' : ActorMethod<[string], undefined>,
  'deleteDraftExclusiveService' : ActorMethod<[string], undefined>,
  'deleteDraftMapMarker' : ActorMethod<[string], undefined>,
  'deleteDraftTestimonial' : ActorMethod<[string], undefined>,
  'deleteExperienceHighlight' : ActorMethod<[string], undefined>,
  'deleteExperienceSection' : ActorMethod<[string], undefined>,
  'deleteSectionImage' : ActorMethod<[string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDraftApartment' : ActorMethod<[string], [] | [Apartment]>,
  'getDraftArtist' : ActorMethod<[string], [] | [Artist]>,
  'getDraftArtwork' : ActorMethod<[string], [] | [Artwork]>,
  'getDraftCityGuideEntry' : ActorMethod<[string], [] | [CityGuideEntry]>,
  'getDraftExclusiveService' : ActorMethod<[string], [] | [ExclusiveService]>,
  'getDraftImprintPage' : ActorMethod<[], LegalPage>,
  'getDraftMapMarker' : ActorMethod<[string], [] | [MapMarker]>,
  'getDraftPrivacyPolicyPage' : ActorMethod<[], LegalPage>,
  'getDraftSiteConfig' : ActorMethod<[], SiteConfig>,
  'getDraftTermsPage' : ActorMethod<[], LegalPage>,
  'getFileReference' : ActorMethod<[string], [] | [FileReference]>,
  'getLiveApartment' : ActorMethod<[string], [] | [Apartment]>,
  'getLiveArtist' : ActorMethod<[string], [] | [Artist]>,
  'getLiveArtwork' : ActorMethod<[string], [] | [Artwork]>,
  'getLiveCityGuideEntry' : ActorMethod<[string], [] | [CityGuideEntry]>,
  'getLiveExclusiveService' : ActorMethod<[string], [] | [ExclusiveService]>,
  'getLiveImprintPage' : ActorMethod<[], LegalPage>,
  'getLiveMapMarker' : ActorMethod<[string], [] | [MapMarker]>,
  'getLivePrivacyPolicyPage' : ActorMethod<[], LegalPage>,
  'getLiveSiteConfig' : ActorMethod<[], SiteConfig>,
  'getLiveTermsPage' : ActorMethod<[], LegalPage>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'listDraftApartments' : ActorMethod<[], Array<Apartment>>,
  'listDraftArtists' : ActorMethod<[], Array<Artist>>,
  'listDraftArtworks' : ActorMethod<[], Array<Artwork>>,
  'listDraftCityGuideEntries' : ActorMethod<[], Array<CityGuideEntry>>,
  'listDraftExclusiveServices' : ActorMethod<[], Array<ExclusiveService>>,
  'listDraftMapMarkers' : ActorMethod<[], Array<MapMarker>>,
  'listDraftTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'listLiveApartments' : ActorMethod<[], Array<Apartment>>,
  'listLiveArtists' : ActorMethod<[], Array<Artist>>,
  'listLiveArtworks' : ActorMethod<[], Array<Artwork>>,
  'listLiveCityGuideEntries' : ActorMethod<[], Array<CityGuideEntry>>,
  'listLiveExclusiveServices' : ActorMethod<[], Array<ExclusiveService>>,
  'listLiveMapMarkers' : ActorMethod<[], Array<MapMarker>>,
  'listLiveTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'permanentlyDeleteApartment' : ActorMethod<[string], undefined>,
  'permanentlyDeleteArtist' : ActorMethod<[string], undefined>,
  'permanentlyDeleteArtwork' : ActorMethod<[string], undefined>,
  'publishChanges' : ActorMethod<[], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'reorderCityGuideEntries' : ActorMethod<[Array<string>], undefined>,
  'reorderExclusiveServices' : ActorMethod<[Array<string>], undefined>,
  'reorderExperienceSections' : ActorMethod<[Array<string>], undefined>,
  'reorderMapMarkers' : ActorMethod<[Array<string>], undefined>,
  'reorderTestimonials' : ActorMethod<[Array<string>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAccentColor' : ActorMethod<[string], undefined>,
  'setApartmentDetailPageBackgroundColor' : ActorMethod<[string], undefined>,
  'setApartmentsPageBackgroundColor' : ActorMethod<[string], undefined>,
  'setArtistDetailPageBackgroundColor' : ActorMethod<[string], undefined>,
  'setArtworkDetailPageBackgroundColor' : ActorMethod<[string], undefined>,
  /**
   * / Set or clear the object-storage key for the Aura Collection main landing image.
   */
  'setAuraCollectionLandingImageKey' : ActorMethod<[[] | [string]], undefined>,
  'setAuraCollectionPageBackgroundColor' : ActorMethod<[string], undefined>,
  'setBookingUrl' : ActorMethod<[string], undefined>,
  'setDefaultAboutImage' : ActorMethod<[string], undefined>,
  'setDefaultApartmentsImage' : ActorMethod<[string], undefined>,
  'setDefaultCollectionImage' : ActorMethod<[string], undefined>,
  'setDefaultExperienceImage' : ActorMethod<[string], undefined>,
  'setDefaultHeroImage' : ActorMethod<[string], undefined>,
  /**
   * / Set or clear the image object-storage key on a draft city guide entry.
   */
  'setDraftCityGuideImageKey' : ActorMethod<[string, [] | [string]], undefined>,
  /**
   * / Set or clear the PDF object-storage key on a draft city guide entry.
   */
  'setDraftCityGuidePdfKey' : ActorMethod<[string, [] | [string]], undefined>,
  /**
   * / Set or clear the image object-storage key on a draft exclusive service.
   */
  'setDraftExclusiveServiceImageKey' : ActorMethod<
    [string, [] | [string]],
    undefined
  >,
  /**
   * / Set or clear the image object-storage key on a draft map marker.
   */
  'setDraftMapMarkerImageKey' : ActorMethod<[string, [] | [string]], undefined>,
  'setFeaturedArtists' : ActorMethod<[Array<string>], undefined>,
  'setFeaturedArtworks' : ActorMethod<[Array<string>], undefined>,
  'setHeaderTextColor' : ActorMethod<[string], undefined>,
  'setLandingPageBackgroundColor' : ActorMethod<[string], undefined>,
  'setLogoDisplayLocation' : ActorMethod<[LogoDisplayLocation], undefined>,
  /**
   * / Store an object-storage key for the uploaded logo (preferred over raw path).
   */
  'setLogoKey' : ActorMethod<[string], undefined>,
  'setLogoSize' : ActorMethod<[bigint], undefined>,
  'setShowAuraCollectionOnLandingPage' : ActorMethod<[boolean], undefined>,
  'setTextColor' : ActorMethod<[string], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updateAboutSection' : ActorMethod<[AboutSection], undefined>,
  'updateApartmentGalleryImages' : ActorMethod<
    [string, Array<string>],
    undefined
  >,
  'updateApartmentsSection' : ActorMethod<[ApartmentsSection], undefined>,
  'updateArtistGalleryImages' : ActorMethod<[string, Array<string>], undefined>,
  'updateArtworkGalleryImages' : ActorMethod<
    [string, Array<string>],
    undefined
  >,
  'updateAuraCollectionSection' : ActorMethod<
    [AuraCollectionSection],
    undefined
  >,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateDraftApartment' : ActorMethod<[Apartment], undefined>,
  'updateDraftArtist' : ActorMethod<[Artist], undefined>,
  'updateDraftArtwork' : ActorMethod<[Artwork], undefined>,
  'updateDraftCityGuideEntry' : ActorMethod<[CityGuideEntry], undefined>,
  'updateDraftExclusiveService' : ActorMethod<[ExclusiveService], undefined>,
  'updateDraftMapMarker' : ActorMethod<[MapMarker], undefined>,
  'updateDraftSiteConfig' : ActorMethod<[SiteConfig], undefined>,
  'updateDraftTestimonial' : ActorMethod<[Testimonial], undefined>,
  'updateExperienceHighlight' : ActorMethod<[Highlight], undefined>,
  'updateExperiencePage' : ActorMethod<[ExperiencePage], undefined>,
  'updateExperienceSection' : ActorMethod<[ExperienceSection], undefined>,
  'updateFooterSection' : ActorMethod<[FooterSection], undefined>,
  'updateHeroSection' : ActorMethod<[HeroSection], undefined>,
  'updateImprintPage' : ActorMethod<[string, string, string], undefined>,
  'updatePrivacyPolicyPage' : ActorMethod<[string, string, string], undefined>,
  'updateSectionTexts' : ActorMethod<[SectionTexts], undefined>,
  'updateTermsPage' : ActorMethod<[string, string, string], undefined>,
  'uploadLogo' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];