/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Apartment = IDL.Record({
  'id' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'bookingUrl' : IDL.Text,
  'photos' : IDL.Vec(IDL.Text),
});
export const Artist = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'galleryImages' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'artworks' : IDL.Vec(IDL.Text),
  'photo' : IDL.Text,
});
export const Artwork = IDL.Record({
  'id' : IDL.Text,
  'galleryImages' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'artistId' : IDL.Text,
  'description' : IDL.Text,
  'photo' : IDL.Text,
  'price' : IDL.Opt(IDL.Nat),
  'isForSale' : IDL.Bool,
});
export const Highlight = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const LayoutOption = IDL.Variant({
  'grid' : IDL.Null,
  'list' : IDL.Null,
  'centered' : IDL.Null,
  'simple' : IDL.Null,
  'leftImage' : IDL.Null,
  'gallery' : IDL.Null,
});
export const ExperienceSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'animationType' : IDL.Text,
  'layout' : LayoutOption,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'videos' : IDL.Vec(IDL.Text),
  'images' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LegalPage = IDL.Record({
  'backgroundColor' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'textColor' : IDL.Text,
});
export const AboutSection = IDL.Record({
  'backgroundColor' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'layout' : LayoutOption,
  'image' : IDL.Text,
  'textColor' : IDL.Text,
});
export const HeroSection = IDL.Record({
  'backgroundColor' : IDL.Text,
  'title' : IDL.Text,
  'layout' : LayoutOption,
  'backgroundImage' : IDL.Text,
  'textColor' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const FooterSection = IDL.Record({
  'backgroundColor' : IDL.Text,
  'contactInfo' : IDL.Text,
  'socialLinks' : IDL.Vec(IDL.Text),
  'layout' : LayoutOption,
  'textColor' : IDL.Text,
});
export const LogoDisplayLocation = IDL.Variant({
  'both' : IDL.Null,
  'footer' : IDL.Null,
  'header' : IDL.Null,
});
export const ApartmentsSection = IDL.Record({
  'backgroundColor' : IDL.Text,
  'title' : IDL.Text,
  'layout' : LayoutOption,
  'description' : IDL.Text,
  'backgroundImage' : IDL.Text,
  'textColor' : IDL.Text,
});
export const CardStyle = IDL.Variant({
  'minimal' : IDL.Null,
  'classic' : IDL.Null,
  'modern' : IDL.Null,
});
export const ExperiencePage = IDL.Record({
  'backgroundColor' : IDL.Text,
  'title' : IDL.Text,
  'layout' : LayoutOption,
  'description' : IDL.Text,
  'highlights' : IDL.Vec(Highlight),
  'backgroundImage' : IDL.Text,
  'sections' : IDL.Vec(ExperienceSection),
  'cardStyle' : CardStyle,
  'textColor' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'contactText' : IDL.Text,
  'socialLinks' : IDL.Vec(SocialLink),
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const SectionTexts = IDL.Record({
  'featuredText' : IDL.Text,
  'discoverText' : IDL.Text,
});
export const AuraCollectionSection = IDL.Record({
  'backgroundColor' : IDL.Text,
  'title' : IDL.Text,
  'contactInfo' : ContactInfo,
  'showOnLandingPage' : IDL.Bool,
  'layout' : LayoutOption,
  'description' : IDL.Text,
  'sectionTexts' : SectionTexts,
  'featuredArtworks' : IDL.Vec(IDL.Text),
  'backgroundImage' : IDL.Text,
  'featuredArtists' : IDL.Vec(IDL.Text),
  'textColor' : IDL.Text,
});
export const SiteConfig = IDL.Record({
  'defaultCollectionImage' : IDL.Text,
  'aboutSection' : AboutSection,
  'heroSection' : HeroSection,
  'footerSection' : FooterSection,
  'artistDetailPageBackgroundColor' : IDL.Text,
  'defaultHeroImage' : IDL.Text,
  'logoDisplayLocation' : LogoDisplayLocation,
  'defaultArtworkImage' : IDL.Text,
  'apartmentsSection' : ApartmentsSection,
  'headerTextColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'logoPath' : IDL.Text,
  'logoSize' : IDL.Nat,
  'language' : IDL.Text,
  'defaultApartmentImage' : IDL.Text,
  'auraCollectionPageBackgroundColor' : IDL.Text,
  'defaultExperienceImage' : IDL.Text,
  'defaultArtistImage' : IDL.Text,
  'experiencePage' : ExperiencePage,
  'contactEmail' : IDL.Text,
  'landingPageBackgroundColor' : IDL.Text,
  'logoPlaceholderPath' : IDL.Text,
  'defaultApartmentsImage' : IDL.Text,
  'apartmentsPageBackgroundColor' : IDL.Text,
  'bookingUrl' : IDL.Text,
  'auraCollectionSection' : AuraCollectionSection,
  'textColor' : IDL.Text,
  'apartmentDetailPageBackgroundColor' : IDL.Text,
  'artworkDetailPageBackgroundColor' : IDL.Text,
  'defaultAboutImage' : IDL.Text,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addDraftApartment' : IDL.Func([Apartment], [], []),
  'addDraftArtist' : IDL.Func([Artist], [], []),
  'addDraftArtwork' : IDL.Func([Artwork], [], []),
  'addExperienceHighlight' : IDL.Func([Highlight], [], []),
  'addExperienceSection' : IDL.Func([ExperienceSection], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDraftApartment' : IDL.Func([IDL.Text], [], []),
  'deleteDraftArtist' : IDL.Func([IDL.Text], [], []),
  'deleteDraftArtwork' : IDL.Func([IDL.Text], [], []),
  'deleteExperienceHighlight' : IDL.Func([IDL.Text], [], []),
  'deleteExperienceSection' : IDL.Func([IDL.Text], [], []),
  'deleteSectionImage' : IDL.Func([IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDraftApartment' : IDL.Func([IDL.Text], [IDL.Opt(Apartment)], ['query']),
  'getDraftArtist' : IDL.Func([IDL.Text], [IDL.Opt(Artist)], ['query']),
  'getDraftArtwork' : IDL.Func([IDL.Text], [IDL.Opt(Artwork)], ['query']),
  'getDraftImprintPage' : IDL.Func([], [LegalPage], ['query']),
  'getDraftPrivacyPolicyPage' : IDL.Func([], [LegalPage], ['query']),
  'getDraftSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
  'getDraftTermsPage' : IDL.Func([], [LegalPage], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getLiveApartment' : IDL.Func([IDL.Text], [IDL.Opt(Apartment)], ['query']),
  'getLiveArtist' : IDL.Func([IDL.Text], [IDL.Opt(Artist)], ['query']),
  'getLiveArtwork' : IDL.Func([IDL.Text], [IDL.Opt(Artwork)], ['query']),
  'getLiveImprintPage' : IDL.Func([], [LegalPage], ['query']),
  'getLivePrivacyPolicyPage' : IDL.Func([], [LegalPage], ['query']),
  'getLiveSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
  'getLiveTermsPage' : IDL.Func([], [LegalPage], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'listDraftApartments' : IDL.Func([], [IDL.Vec(Apartment)], ['query']),
  'listDraftArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
  'listDraftArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'listLiveApartments' : IDL.Func([], [IDL.Vec(Apartment)], ['query']),
  'listLiveArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
  'listLiveArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
  'permanentlyDeleteApartment' : IDL.Func([IDL.Text], [], []),
  'permanentlyDeleteArtist' : IDL.Func([IDL.Text], [], []),
  'permanentlyDeleteArtwork' : IDL.Func([IDL.Text], [], []),
  'publishChanges' : IDL.Func([], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'reorderExperienceSections' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAccentColor' : IDL.Func([IDL.Text], [], []),
  'setApartmentDetailPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
  'setApartmentsPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
  'setArtistDetailPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
  'setArtworkDetailPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
  'setAuraCollectionPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
  'setBookingUrl' : IDL.Func([IDL.Text], [], []),
  'setDefaultAboutImage' : IDL.Func([IDL.Text], [], []),
  'setDefaultApartmentsImage' : IDL.Func([IDL.Text], [], []),
  'setDefaultCollectionImage' : IDL.Func([IDL.Text], [], []),
  'setDefaultExperienceImage' : IDL.Func([IDL.Text], [], []),
  'setDefaultHeroImage' : IDL.Func([IDL.Text], [], []),
  'setFeaturedArtists' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setFeaturedArtworks' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'setHeaderTextColor' : IDL.Func([IDL.Text], [], []),
  'setLandingPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
  'setLogoDisplayLocation' : IDL.Func([LogoDisplayLocation], [], []),
  'setLogoSize' : IDL.Func([IDL.Nat], [], []),
  'setShowAuraCollectionOnLandingPage' : IDL.Func([IDL.Bool], [], []),
  'setTextColor' : IDL.Func([IDL.Text], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAboutSection' : IDL.Func([AboutSection], [], []),
  'updateApartmentGalleryImages' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateApartmentsSection' : IDL.Func([ApartmentsSection], [], []),
  'updateArtistGalleryImages' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'updateArtworkGalleryImages' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateAuraCollectionSection' : IDL.Func([AuraCollectionSection], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateDraftApartment' : IDL.Func([Apartment], [], []),
  'updateDraftArtist' : IDL.Func([Artist], [], []),
  'updateDraftArtwork' : IDL.Func([Artwork], [], []),
  'updateDraftSiteConfig' : IDL.Func([SiteConfig], [], []),
  'updateExperienceHighlight' : IDL.Func([Highlight], [], []),
  'updateExperiencePage' : IDL.Func([ExperiencePage], [], []),
  'updateExperienceSection' : IDL.Func([ExperienceSection], [], []),
  'updateFooterSection' : IDL.Func([FooterSection], [], []),
  'updateHeroSection' : IDL.Func([HeroSection], [], []),
  'updateImprintPage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePrivacyPolicyPage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSectionTexts' : IDL.Func([SectionTexts], [], []),
  'updateTermsPage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'uploadLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Apartment = IDL.Record({
    'id' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'bookingUrl' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
  });
  const Artist = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'galleryImages' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'artworks' : IDL.Vec(IDL.Text),
    'photo' : IDL.Text,
  });
  const Artwork = IDL.Record({
    'id' : IDL.Text,
    'galleryImages' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'artistId' : IDL.Text,
    'description' : IDL.Text,
    'photo' : IDL.Text,
    'price' : IDL.Opt(IDL.Nat),
    'isForSale' : IDL.Bool,
  });
  const Highlight = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const LayoutOption = IDL.Variant({
    'grid' : IDL.Null,
    'list' : IDL.Null,
    'centered' : IDL.Null,
    'simple' : IDL.Null,
    'leftImage' : IDL.Null,
    'gallery' : IDL.Null,
  });
  const ExperienceSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'animationType' : IDL.Text,
    'layout' : LayoutOption,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'videos' : IDL.Vec(IDL.Text),
    'images' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LegalPage = IDL.Record({
    'backgroundColor' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'textColor' : IDL.Text,
  });
  const AboutSection = IDL.Record({
    'backgroundColor' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'layout' : LayoutOption,
    'image' : IDL.Text,
    'textColor' : IDL.Text,
  });
  const HeroSection = IDL.Record({
    'backgroundColor' : IDL.Text,
    'title' : IDL.Text,
    'layout' : LayoutOption,
    'backgroundImage' : IDL.Text,
    'textColor' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const FooterSection = IDL.Record({
    'backgroundColor' : IDL.Text,
    'contactInfo' : IDL.Text,
    'socialLinks' : IDL.Vec(IDL.Text),
    'layout' : LayoutOption,
    'textColor' : IDL.Text,
  });
  const LogoDisplayLocation = IDL.Variant({
    'both' : IDL.Null,
    'footer' : IDL.Null,
    'header' : IDL.Null,
  });
  const ApartmentsSection = IDL.Record({
    'backgroundColor' : IDL.Text,
    'title' : IDL.Text,
    'layout' : LayoutOption,
    'description' : IDL.Text,
    'backgroundImage' : IDL.Text,
    'textColor' : IDL.Text,
  });
  const CardStyle = IDL.Variant({
    'minimal' : IDL.Null,
    'classic' : IDL.Null,
    'modern' : IDL.Null,
  });
  const ExperiencePage = IDL.Record({
    'backgroundColor' : IDL.Text,
    'title' : IDL.Text,
    'layout' : LayoutOption,
    'description' : IDL.Text,
    'highlights' : IDL.Vec(Highlight),
    'backgroundImage' : IDL.Text,
    'sections' : IDL.Vec(ExperienceSection),
    'cardStyle' : CardStyle,
    'textColor' : IDL.Text,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const ContactInfo = IDL.Record({
    'contactText' : IDL.Text,
    'socialLinks' : IDL.Vec(SocialLink),
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SectionTexts = IDL.Record({
    'featuredText' : IDL.Text,
    'discoverText' : IDL.Text,
  });
  const AuraCollectionSection = IDL.Record({
    'backgroundColor' : IDL.Text,
    'title' : IDL.Text,
    'contactInfo' : ContactInfo,
    'showOnLandingPage' : IDL.Bool,
    'layout' : LayoutOption,
    'description' : IDL.Text,
    'sectionTexts' : SectionTexts,
    'featuredArtworks' : IDL.Vec(IDL.Text),
    'backgroundImage' : IDL.Text,
    'featuredArtists' : IDL.Vec(IDL.Text),
    'textColor' : IDL.Text,
  });
  const SiteConfig = IDL.Record({
    'defaultCollectionImage' : IDL.Text,
    'aboutSection' : AboutSection,
    'heroSection' : HeroSection,
    'footerSection' : FooterSection,
    'artistDetailPageBackgroundColor' : IDL.Text,
    'defaultHeroImage' : IDL.Text,
    'logoDisplayLocation' : LogoDisplayLocation,
    'defaultArtworkImage' : IDL.Text,
    'apartmentsSection' : ApartmentsSection,
    'headerTextColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'logoPath' : IDL.Text,
    'logoSize' : IDL.Nat,
    'language' : IDL.Text,
    'defaultApartmentImage' : IDL.Text,
    'auraCollectionPageBackgroundColor' : IDL.Text,
    'defaultExperienceImage' : IDL.Text,
    'defaultArtistImage' : IDL.Text,
    'experiencePage' : ExperiencePage,
    'contactEmail' : IDL.Text,
    'landingPageBackgroundColor' : IDL.Text,
    'logoPlaceholderPath' : IDL.Text,
    'defaultApartmentsImage' : IDL.Text,
    'apartmentsPageBackgroundColor' : IDL.Text,
    'bookingUrl' : IDL.Text,
    'auraCollectionSection' : AuraCollectionSection,
    'textColor' : IDL.Text,
    'apartmentDetailPageBackgroundColor' : IDL.Text,
    'artworkDetailPageBackgroundColor' : IDL.Text,
    'defaultAboutImage' : IDL.Text,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addDraftApartment' : IDL.Func([Apartment], [], []),
    'addDraftArtist' : IDL.Func([Artist], [], []),
    'addDraftArtwork' : IDL.Func([Artwork], [], []),
    'addExperienceHighlight' : IDL.Func([Highlight], [], []),
    'addExperienceSection' : IDL.Func([ExperienceSection], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDraftApartment' : IDL.Func([IDL.Text], [], []),
    'deleteDraftArtist' : IDL.Func([IDL.Text], [], []),
    'deleteDraftArtwork' : IDL.Func([IDL.Text], [], []),
    'deleteExperienceHighlight' : IDL.Func([IDL.Text], [], []),
    'deleteExperienceSection' : IDL.Func([IDL.Text], [], []),
    'deleteSectionImage' : IDL.Func([IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDraftApartment' : IDL.Func([IDL.Text], [IDL.Opt(Apartment)], ['query']),
    'getDraftArtist' : IDL.Func([IDL.Text], [IDL.Opt(Artist)], ['query']),
    'getDraftArtwork' : IDL.Func([IDL.Text], [IDL.Opt(Artwork)], ['query']),
    'getDraftImprintPage' : IDL.Func([], [LegalPage], ['query']),
    'getDraftPrivacyPolicyPage' : IDL.Func([], [LegalPage], ['query']),
    'getDraftSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
    'getDraftTermsPage' : IDL.Func([], [LegalPage], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getLiveApartment' : IDL.Func([IDL.Text], [IDL.Opt(Apartment)], ['query']),
    'getLiveArtist' : IDL.Func([IDL.Text], [IDL.Opt(Artist)], ['query']),
    'getLiveArtwork' : IDL.Func([IDL.Text], [IDL.Opt(Artwork)], ['query']),
    'getLiveImprintPage' : IDL.Func([], [LegalPage], ['query']),
    'getLivePrivacyPolicyPage' : IDL.Func([], [LegalPage], ['query']),
    'getLiveSiteConfig' : IDL.Func([], [SiteConfig], ['query']),
    'getLiveTermsPage' : IDL.Func([], [LegalPage], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'listDraftApartments' : IDL.Func([], [IDL.Vec(Apartment)], ['query']),
    'listDraftArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
    'listDraftArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'listLiveApartments' : IDL.Func([], [IDL.Vec(Apartment)], ['query']),
    'listLiveArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
    'listLiveArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
    'permanentlyDeleteApartment' : IDL.Func([IDL.Text], [], []),
    'permanentlyDeleteArtist' : IDL.Func([IDL.Text], [], []),
    'permanentlyDeleteArtwork' : IDL.Func([IDL.Text], [], []),
    'publishChanges' : IDL.Func([], [], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'reorderExperienceSections' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAccentColor' : IDL.Func([IDL.Text], [], []),
    'setApartmentDetailPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
    'setApartmentsPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
    'setArtistDetailPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
    'setArtworkDetailPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
    'setAuraCollectionPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
    'setBookingUrl' : IDL.Func([IDL.Text], [], []),
    'setDefaultAboutImage' : IDL.Func([IDL.Text], [], []),
    'setDefaultApartmentsImage' : IDL.Func([IDL.Text], [], []),
    'setDefaultCollectionImage' : IDL.Func([IDL.Text], [], []),
    'setDefaultExperienceImage' : IDL.Func([IDL.Text], [], []),
    'setDefaultHeroImage' : IDL.Func([IDL.Text], [], []),
    'setFeaturedArtists' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setFeaturedArtworks' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setHeaderTextColor' : IDL.Func([IDL.Text], [], []),
    'setLandingPageBackgroundColor' : IDL.Func([IDL.Text], [], []),
    'setLogoDisplayLocation' : IDL.Func([LogoDisplayLocation], [], []),
    'setLogoSize' : IDL.Func([IDL.Nat], [], []),
    'setShowAuraCollectionOnLandingPage' : IDL.Func([IDL.Bool], [], []),
    'setTextColor' : IDL.Func([IDL.Text], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAboutSection' : IDL.Func([AboutSection], [], []),
    'updateApartmentGalleryImages' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateApartmentsSection' : IDL.Func([ApartmentsSection], [], []),
    'updateArtistGalleryImages' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateArtworkGalleryImages' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateAuraCollectionSection' : IDL.Func([AuraCollectionSection], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateDraftApartment' : IDL.Func([Apartment], [], []),
    'updateDraftArtist' : IDL.Func([Artist], [], []),
    'updateDraftArtwork' : IDL.Func([Artwork], [], []),
    'updateDraftSiteConfig' : IDL.Func([SiteConfig], [], []),
    'updateExperienceHighlight' : IDL.Func([Highlight], [], []),
    'updateExperiencePage' : IDL.Func([ExperiencePage], [], []),
    'updateExperienceSection' : IDL.Func([ExperienceSection], [], []),
    'updateFooterSection' : IDL.Func([FooterSection], [], []),
    'updateHeroSection' : IDL.Func([HeroSection], [], []),
    'updateImprintPage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePrivacyPolicyPage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSectionTexts' : IDL.Func([SectionTexts], [], []),
    'updateTermsPage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'uploadLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };